driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.9
  client_rb:
    diff_disabled: true
    chef_license: "accept-silent"
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-9

suites:
  - name: binaries
    run_list:
      - recipe[test::shifter_compile]
      - recipe[test::shifterimg_install]
      - recipe[test::shifter_install]
