driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-8
  - name: debian-9
  - name: centos-6
  - name: centos-7

suites:
  - name: binaries
    run_list:
      - recipe[test::shifter_compile]
  - name: shifter-runtime
    run_list:
      - recipe[test::shifter_install]
  - name: shifter-image-gateway
    run_list:
      - recipe[test::shifterimg_install]
