driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-9

suites:
  - name: binaries
    run_list:
      - recipe[test::shifter_compile]
      - recipe[test::shifterimg_install]
      - recipe[test::shifter_install]
