driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: false

platforms:
  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  - name: centos-6
    driver:
      image: dokken/centos-6
      intermediate_instructions:
        - RUN /usr/bin/yum install -y epel-release
  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/yum install -y epel-release
