name 'shifter'
maintainer 'Manuel Torrinha'
maintainer_email 'manuel.torrinha@tecnico.ulisboa.pt'
license 'Apache-2.0'
description 'Installs/Configures shifter'
long_description 'Installs/Configures shifter'
version '0.2.4'
chef_version '>= 14.0'
issues_url 'https://github.com/t0rrant/cookbook-shifter/issues'
source_url 'https://github.com/t0rrant/cookbook-shifter'

supports 'ubuntu', '>= 14.0'
supports 'debian', '>= 9.0'
supports 'centos', '>= 6.0'

depends 'tar', '~> 2.0'
